apiVersion: v1
kind: Service
metadata:
  name: kanister-visualiser-service
spec:
  selector:
    app: kanister-visualiser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use 'NodePort' or 'ClusterIP' based on your needs
