apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanister-visualiser-role
  namespace: kanister
rules:
- apiGroups: ["cr.kanister.io"]
  resources: ["profiles", "actionsets", "blueprints"]
  verbs: ["get", "list"]  # Define the necessary verbs (actions) for Kanister Profiles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kanister-visualiser-rolebinding
  namespace: kanister
subjects:
- kind: ServiceAccount
  name: kanister-visualiser-sa
  namespace: kanister
roleRef:
  kind: Role
  name: kanister-visualiser-role
  apiGroup: rbac.authorization.k8s.io
